"""Initial migration

Revision ID: 4b8ce7e3fd93
Revises: 
Create Date: 2026-09-05 11:00:50.599175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8ce7e3fd93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_result', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('event_sequence_counter', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    op.create_index('idx_task_runs_correlation', 'task_runs', ['correlation_id'], unique=False)
    op.create_index('idx_task_runs_status_created', 'task_runs', ['status', 'created_at'], unique=False)
    op.create_table('execution_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('llm_total_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('tool_success_count', sa.Integer(), nullable=False),
    sa.Column('tool_failure_count', sa.Integer(), nullable=False),
    sa.Column('agent_transition_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('feedback_loop_count', sa.Integer(), nullable=False),
    sa.Column('per_agent_durations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('per_tool_durations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_run_id')
    )
    op.create_index('idx_em_task_run', 'execution_metrics', ['task_run_id'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('parent_node_id', sa.UUID(), nullable=True),
    sa.Column('edge_label', sa.String(length=100), nullable=True),
    sa.Column('edge_type', sa.String(length=20), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_node_id'], ['workflow_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wfn_parent', 'workflow_nodes', ['parent_node_id'], unique=False)
    op.create_index('idx_wfn_task_run', 'workflow_nodes', ['task_run_id'], unique=False)
    op.create_index('idx_wfn_task_status', 'workflow_nodes', ['task_run_id', 'status'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_node_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_run_id', 'sequence_number', name='uq_task_seq')
    )
    op.create_index('idx_ae_correlation', 'agent_events', ['correlation_id'], unique=False)
    op.create_index('idx_ae_task_seq', 'agent_events', ['task_run_id', 'sequence_number'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_node_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ti_celery', 'tool_invocations', ['celery_task_id'], unique=False)
    op.create_index('idx_ti_task_run', 'tool_invocations', ['task_run_id'], unique=False)
    op.create_index('idx_ti_tool_status', 'tool_invocations', ['tool_name', 'status'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_node_id', sa.UUID(), nullable=True),
    sa.Column('tool_invocation_id', sa.UUID(), nullable=True),
    sa.Column('error_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('stack_trace', sa.String(), nullable=True),
    sa.Column('context_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('is_recovered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_invocation_id'], ['tool_invocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_el_severity', 'error_logs', ['severity', 'created_at'], unique=False)
    op.create_index('idx_el_task_run', 'error_logs', ['task_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_el_task_run', table_name='error_logs')
    op.drop_index('idx_el_severity', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index('idx_ti_tool_status', table_name='tool_invocations')
    op.drop_index('idx_ti_task_run', table_name='tool_invocations')
    op.drop_index('idx_ti_celery', table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index('idx_ae_task_seq', table_name='agent_events')
    op.drop_index('idx_ae_correlation', table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index('idx_wfn_task_status', table_name='workflow_nodes')
    op.drop_index('idx_wfn_task_run', table_name='workflow_nodes')
    op.drop_index('idx_wfn_parent', table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index('idx_em_task_run', table_name='execution_metrics')
    op.drop_table('execution_metrics')
    op.drop_index('idx_task_runs_status_created', table_name='task_runs')
    op.drop_index('idx_task_runs_correlation', table_name='task_runs')
    op.drop_table('task_runs')
    # ### end Alembic commands ###
