'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, History, Network, Plus, Sparkles } from 'lucide-react';
import AppShell from '@/components/AppShell';
import RunCard from '@/components/RunCard';
import { fetchTasks, Task } from '@/lib/api';

export default function DashboardPage() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void fetchTasks().then(setTasks).catch(() => setError('Unable to load your workflows.')); }, []);
  return <AppShell><main className="mx-auto max-w-[1500px] px-5 py-10 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium uppercase tracking-[0.18em] text-emerald-300">Control center</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-white">Build with visibility.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Start a workflow, inspect every agent transition, and return to the full execution history whenever you need it.</p></div><Link href="/workspace/new" className="inline-flex items-center justify-center gap-2 bg-emerald-300 px-5 py-3 text-sm font-semibold text-slate-950"><Plus size={16} aria-hidden="true" /> New workflow</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="border border-white/10 bg-[#111a23] p-5"><Network size={18} className="text-emerald-300" aria-hidden="true" /><p className="mt-5 text-2xl font-semibold text-white">{tasks.length}</p><p className="mt-1 text-xs text-slate-500">Saved workflow runs</p></div><div className="border border-white/10 bg-[#111a23] p-5"><Sparkles size={18} className="text-emerald-300" aria-hidden="true" /><p className="mt-5 text-2xl font-semibold text-white">{tasks.filter((task) => task.status === 'COMPLETED').length}</p><p className="mt-1 text-xs text-slate-500">Completed outputs</p></div><div className="border border-white/10 bg-[#111a23] p-5"><History size={18} className="text-emerald-300" aria-hidden="true" /><p className="mt-5 text-2xl font-semibold text-white">Private</p><p className="mt-1 text-xs text-slate-500">Your execution history</p></div></div><div className="mt-12 flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Recent workflows</h2><Link href="/history" className="inline-flex items-center gap-2 text-sm text-emerald-300 hover:text-emerald-200">View history <ArrowRight size={15} aria-hidden="true" /></Link></div>{error ? <p role="alert" className="mt-5 border border-red-300/30 bg-red-300/10 p-4 text-sm text-red-200">{error}</p> : tasks.length === 0 ? <div className="mt-5 border border-dashed border-white/15 p-12 text-center"><p className="text-sm text-slate-400">Your first workflow is one clear prompt away.</p><Link href="/workspace/new" className="mt-4 inline-flex text-sm text-emerald-300">Create a workflow <ArrowRight size={15} className="ml-2" aria-hidden="true" /></Link></div> : <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tasks.slice(0, 6).map((task) => <RunCard key={task.id} task={task} />)}</div>}</main></AppShell>;
}
